export const tagSchema = {
  volunteering: { bg: "#F3DCFF", fg: "#C050FA" },
  charity: { bg: "#F6FFAF", fg: "#3D4117" },
  science: { bg: "#EAF2FF", fg: "#2575E5" },
  tech: { bg: "#fff5db", fg: "#FACA52" },
  math: { bg: "#ffdbdb", fg: "#FA5252" },
  engineering: { bg: "#acdbf9", fg: "#3493cf" },
  writing: { bg: "#ffdbf9", fg: "#FA52DE" },
  sports: { bg: "#ffe9db", fg: "#FA9252" },
  health: { bg: "#dcdbff", fg: "#5752FA" },
  politics: { bg: "#ffabe0", fg: "#ff5dc3" },
  music: { bg: "#ffc9ec", fg: "#FA52BF" },
  arts: { bg: "#e3f2ff", fg: "#50A9F7" },
  "performing arts": { bg: "#ffc7a3", fg: "#E16C23" },
  "academic competition": { bg: "#fcf490", fg: "#a9a123" },
  tutoring: { bg: "#dbffe1", fg: "#2cd047" },
  culture: { bg: "#e5e5e5", fg: "#5c5c5c" },
  socializing: { bg: "#d0cfff", fg: "#5b59d5" },
  debate: { bg: "#cffff9", fg: "#19a090" },
  business: { bg: "#fdef6c", fg: "#7b721e" },
  community: { bg: "#dee1ff", fg: "#5560d8" },
  education: { bg: "#dbfeff", fg: "#26c5ca" },
  "public speaking": { bg: "#ffdef0", fg: "#D8559D" },
  "social activism": { bg: "#fff4de", fg: "#b98b2f" },
};
